# Generated by Django 3.2 on 2022-11-27 12:57

from django.db import migrations


def forward_func(apps, schema_editor):
    News = apps.get_model("mainapp", "News")

    New


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [migrations.RunPython()]
